### ISSUE TITLE
Sniper Slingshot

### ISSUE THREAD

**Issue by VulfVolki** [Pravpro/Beasts-Domain#19]
As an option we can make a version of the slingshot that just aims and hits and object without a trajectory arc. It might be easier to use that the one with the arc.

**Comment by Pravpro** [comment]
I'll look into this since I already worked on the slingshot!

**Comment by VulfVolki** [comment]
Alright then! Hopefully we can test the two versions soon so we can spend more time fine tuning

**Comment by Pravpro** [comment]
Sniper works like a charm! Just need to debug the Raycast. Closing issue since the whole feature has overall been completed!
